### ISSUE TITLE
Release version is not correct according to description

### ISSUE THREAD

**Issue by delipl** [mabrobotics/mdtool#19]
The latest version of release  downloads files with 1.4.0:
https://github.com/mabrobotics/mdtool/actions/runs/9316243858/job/25644075734#step:4:169

https://github.com/mabrobotics/mdtool/releases/tag/v1.4.1

[Screencast from 31.05.2024 15:17:30.webm](https://github.com/mabrobotics/mdtool/assets/33808634/5d8f0f82-5fd1-45c6-b2af-3b56db8a5aad)

**Comment by jakubmatyszczak** [comment]
Hello @delipl, thank you for your report.
The filename being downloaded is wrong, as it seems we forgot to update the software version in the release. All files are updated, and the `mdtool` will work with HW3.0 boards as advertised.

We will fix version this issue soon. Sorry for the incoviniece!

**Comment by jakubmatyszczak** [comment]
Fixed in #21
